### ISSUE TITLE
This version of ChromeDriver only supports Chrome version XX

### ISSUE THREAD

**Issue by markplus** [smf33/FlickrFollowerBot#1]
How to solve this error?

## ENDED IN ERROR : session not created: This version of ChromeDriver only supports Chrome version 78 (SessionNotCreated)

**Comment by smf33** [comment]
Hi,
chromedriver must match your chrome version.
Update the chromedriver package (best idea) to match your chrome or use
chrome version 78.

**Comment by smf33** [comment]
I also updated package btw for supporting more recent chrome

**Comment by markplus** [comment]
how do i update? can you tell me how to do it?

Il giorno sab 7 mar 2020 alle ore 14:24 SmF33 <notifications@github.com> ha
scritto:

**Comment by markplus** [comment]
C:\Program
Files\dotnet\sdk\3.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(127,5):
error NETSDK1045: la versione corrente di .NET SDK non supporta .NET Core
3.1 come destinazione. Impostare come destinazione .NET Core 3.0 o una
versione precedente oppure usare una versione di .NET SDK che supporta .NET
Core 3.1.
[C:\Users\Downloads\FlickrFollowerBot-master\FlickrFollowerBot.csproj]

**Comment by smf33** [comment]
Hi,
Very easy
First, start your message by a « hi »
Then, « install .net core 3.1, like said in the readme
Last but not least, end your message by a « tx, i know u may have best
thing to do than reply to theses questions, by ! »
By

**Comment by markplus** [comment]
hello, solved thanks for your support

**Comment by smf33** [comment]
Hi,
So, what is exactly your chrome version and dotnet sdk version exactly ?
I just tested from my chrome auto updated version and it was working, both
from dotnet or docker-compose.
Add your log plz also.
Do u use the latest code source of the repo also ?
