### ISSUE TITLE
User can't fav anymore

### ISSUE THREAD

**Issue by aurel2222** [smf33/FlickrFollowerBot#6]
Hi,
When trying to fav from PhotoToFav List, it faves the first picture and then the following message appears :

_GET https://www.flickr.com/photos/xxxxxxxxxxxxxxxxxxxxxxxx/
ACTION STOPED : SEEMS USER (https://www.flickr.com/photos/xxxxxxxxxxxxxxxxxxxxxxx) CAN'T FAV ANYMORE_

(the both adresses are the same)

It appears whatever source is used (user flow, explore).

Trying to find what happens, but you're better than me :)

Thanks for help !

**Comment by aurel2222** [comment]
It seems it doesn't detect already faved icon.
Maybe CSSphotofaved changed
But can't find the new one...

Edit : good hypothesis... 👍 

In JSON change to this values :
"CssPhotoFave": ".fave-view",
"CssPhotoFaved": ".fave-star.is-faved",

**Comment by smf33** [comment]
Hi,
yeah the CssPhotoFaved have been updated by flickr : it isn t anymore a SPAN but a A :-)
Nice debug 👍

**Comment by smf33** [comment]
But is CssPhotoFave update realy required ???

**Comment by aurel2222** [comment]
Hello,
I'm reopening the issue because same problem, same messages. But, it doesn't seems the CSS changed...
It is able to fav but after few (1 to 5) favs it is stopping.

This time, i'm out of idea :/

Still invistigating but any idea would help :)

thanks a lot.

Maybe it is happening in this part of the code :
```
// fav issue detection
				if (!inError && !Selenium.GetElements(Config.CssPhotoFaved).Any()) // will wait a little if required because it s an expected state
				{
					WaitHumanizer();// give a last chance...
					if (!Selenium.GetElements(Config.CssPhotoFaved, true, true).Any()) // will wait a little if required because it s an expected state
					{
						Log.LogWarning("ACTION STOPED : SEEMS USER ({0}) CAN'T FAV ANYMORE", url);
                      			inError = true;
```

**Comment by aurel2222** [comment]
after digging, it seems it doesn't detect when a picture is already faved. I think it is coming from the CssPhotoFaved but I can't find the new one.
The old one seems to be there too.... :-/

 CssPhotoFaved = .is-faved

👍
