### ISSUE TITLE
Cookies Window Pop Up

### ISSUE THREAD

**Issue by Arran-Code** [smf33/FlickrFollowerBot#8]
Because this performs the window in Incognito, during part of the operation you get the "Accept Cookies" window. The code seems to error and not run because the window pops up and its unable to click the next button

# DOCONTACTSUNFOLLOW...
GET https://www.flickr.com/photos/EXAMPLE/
ACTION STOPED : element click intercepted: Element <button class="follow is-following white">...</button> is not clickable at point (702, 218). Other element would receive the click: <iframe src="https://consent-pref.trustarc.com/?type=flickr_iab&amp;layout=iab&amp;site=flickr.com&amp;action=notice&amp;country=gb&amp;locale=en&amp;behavior=expressed&amp;gtm=1&amp;iab=true&amp;irm=undefined&amp;from=https://consent.trustarc.com/" id="pop-frame007670291205188273" title="TrustArc Cookie Consent Manager" tabindex="1" scrolling="no" style="border: 0px; border-radius: 2px; overflow: hidden; background: rgb(255, 255, 255); display: block; position: absolute; top: 0px; left: 0px; width: 100%; height: 985px;"></iframe>
  (Session info: chrome=89.0.4389.90)
OpenQA.Selenium.ElementClickInterceptedException: element click intercepted: Element <button class="follow is-following white">...</button> is not clickable at point (702, 218). Other element would receive the click: <iframe src="https://consent-pref.trustarc.com/?type=flickr_iab&amp;layout=iab&amp;site=flickr.com&amp;action=notice&amp;country=gb&amp;locale=en&amp;behavior=expressed&amp;gtm=1&amp;iab=true&amp;irm=undefined&amp;from=https://consent.trustarc.com/" id="pop-frame007670291205188273" title="TrustArc Cookie Consent Manager" tabindex="1" scrolling="no" style="border: 0px; border-radius: 2px; overflow: hidden; background: rgb(255, 255, 255); display: block; position: absolute; top: 0px; left: 0px; width: 100%; height: 985px;"></iframe>
  (Session info: chrome=89.0.4389.90)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Click()
   at FlickrFollowerBot.SeleniumWrapper.Click(String cssSelector) in C:\Users\Arran\Downloads\Flickr\SeleniumWrapper.cs:line 128
   at FlickrFollowerBot.FollowerBot.DoContactsUnfollow() in C:\Users\Arran\Downloads\Flickr\FollowerBot.Actions.cs:line 479
$ContactsToUnfollow -1
# SAVE...
SAVING USER JSON
## ENDED OK

**Comment by smf33** [comment]
Hi,
The Accept Cookies windows is managed by the bot, but sometime IG update
the CSS key and even popup startup order.
First, you can start the bot in normal (not chromeless) mode, and click if
there is an strangebehavor,
firsb bis, you can also do the authentication "manualy" (the bot wait you
to login and so clik when necesary)
second, you can enable the crash dump that will provide the window
screenshoot and also the dynamic html dump, allowing to easily update the
key in the json file.
I curently use the bot, they use cookie session, so the 1st login process
doesn't occur offen in my place.
Note that you may be in incognito (like in fact any session managed by
selenium bot) it s totaly ok.

i may check this "new user/session" process later but not a lot of time
lately, hope theses hint will help you.
Tx
